2025-06-21T16:55:37.201996037Z Using cached packaging-25.0-py3-none-any.whl (66 kB)
2025-06-21T16:55:37.214151721Z Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
2025-06-21T16:55:37.445002321Z Installing collected packages: urllib3, tzlocal, typing-extensions, soupsieve, six, python-http-client, psycopg2-binary, packaging, markupsafe, itsdangerous, idna, greenlet, dnspython, click, charset_normalizer, certifi, blinker, wtforms, werkzeug, sqlalchemy, requests, jinja2, gunicorn, email-validator, ecdsa, beautifulsoup4, apscheduler, sendgrid, flask, flask-wtf, flask-sqlalchemy, flask-mail, flask-login
2025-06-21T16:55:58.224375436Z Successfully installed apscheduler-3.11.0 beautifulsoup4-4.13.4 blinker-1.9.0 certifi-2025.6.15 charset_normalizer-3.4.2 click-8.2.1 dnspython-2.7.0 ecdsa-0.19.1 email-validator-2.2.0 flask-3.1.1 flask-login-0.6.3 flask-mail-0.10.0 flask-sqlalchemy-3.1.1 flask-wtf-1.2.2 greenlet-3.2.3 gunicorn-23.0.0 idna-3.10 itsdangerous-2.2.0 jinja2-3.1.6 markupsafe-3.0.2 packaging-25.0 psycopg2-binary-2.9.10 python-http-client-3.3.7 requests-2.32.4 sendgrid-6.12.4 six-1.17.0 soupsieve-2.7 sqlalchemy-2.0.41 typing-extensions-4.14.0 tzlocal-5.3.1 urllib3-2.5.0 werkzeug-3.1.3 wtforms-3.2.1
2025-06-21T16:55:58.754702631Z 
2025-06-21T16:55:58.754722311Z [notice] A new release of pip is available: 24.0 -> 25.1.1
2025-06-21T16:55:58.754726571Z [notice] To update, run: pip install --upgrade pip
2025-06-21T16:56:23.919326732Z ==> Uploading build...
2025-06-21T16:56:51.499662762Z ==> Uploaded in 12.1s. Compression took 15.5s
2025-06-21T16:56:51.629058992Z ==> Build successful ðŸŽ‰
2025-06-21T16:56:59.584837734Z ==> Deploying...
2025-06-21T16:58:10.302368341Z ==> Your service is live ðŸŽ‰
2025-06-21T16:59:01.329471924Z DEBUG:apscheduler.scheduler:Next wakeup is due at 2025-06-21 17:00:01.319828+00:00 (in 59.991102 seconds)
2025-06-21T16:59:01.331764202Z DEBUG:root:Could not check for new jobs: (sqlite3.OperationalError) no such table: scheduled_job
2025-06-21T16:59:01.331792873Z [SQL: SELECT scheduled_job.id AS scheduled_job_id, scheduled_job.name AS scheduled_job_name, scheduled_job.scheduled_time AS scheduled_job_scheduled_time, scheduled_job.status AS scheduled_job_status, scheduled_job.created_at AS scheduled_job_created_at, scheduled_job.updated_at AS scheduled_job_updated_at, scheduled_job.user_id AS scheduled_job_user_id, scheduled_job.template_id AS scheduled_job_template_id, scheduled_job.segment_id AS scheduled_job_segment_id, scheduled_job.smtp_config_id AS scheduled_job_smtp_config_id, scheduled_job.from_email AS scheduled_job_from_email, scheduled_job.from_name AS scheduled_job_from_name, scheduled_job.started_at AS scheduled_job_started_at, scheduled_job.completed_at AS scheduled_job_completed_at, scheduled_job.current_batch AS scheduled_job_current_batch, scheduled_job.batch_size AS scheduled_job_batch_size, scheduled_job.total_emails AS scheduled_job_total_emails, scheduled_job.sent_emails AS scheduled_job_sent_emails, scheduled_job.failed_emails AS scheduled_job_failed_emails, scheduled_job.opened_emails AS scheduled_job_opened_emails, scheduled_job.clicked_emails AS scheduled_job_clicked_emails, scheduled_job.sending_started_at AS scheduled_job_sending_started_at, scheduled_job.sending_completed_at AS scheduled_job_sending_completed_at, scheduled_job.avg_sending_rate AS scheduled_job_avg_sending_rate, scheduled_job.use_optimal_time AS scheduled_job_use_optimal_time, scheduled_job.optimal_time_window_start AS scheduled_job_optimal_time_window_start, scheduled_job.optimal_time_window_end AS scheduled_job_optimal_time_window_end, scheduled_job.optimal_day_preference AS scheduled_job_optimal_day_preference, scheduled_job.actual_send_time AS scheduled_job_actual_send_time 
2025-06-21T16:59:01.331799613Z FROM scheduled_job 
2025-06-21T16:59:01.331804963Z WHERE scheduled_job.status = ? AND scheduled_job.scheduled_time > ?]
2025-06-21T16:59:01.331810414Z [parameters: ('scheduled', '2025-06-21 16:59:01.323339')]
2025-06-21T16:59:01.331814874Z (Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-21T16:59:01.33260551Z INFO:apscheduler.executors.default:Job "check_for_new_jobs (trigger: interval[0:01:00], next run at: 2025-06-21 17:00:01 UTC)" executed successfully
2025-06-21T17:00:01.324694976Z DEBUG:apscheduler.scheduler:Looking for jobs to run
2025-06-21T17:00:01.324724547Z DEBUG:apscheduler.scheduler:Next wakeup is due at 2025-06-21 17:01:01.319828+00:00 (in 59.997228 seconds)
2025-06-21T17:00:01.324741558Z INFO:apscheduler.executors.default:Running job "check_for_new_jobs (trigger: interval[0:01:00], next run at: 2025-06-21 17:01:01 UTC)" (scheduled at 2025-06-21 17:00:01.319828+00:00)
2025-06-21T17:00:01.32599406Z DEBUG:root:Could not check for new jobs: (sqlite3.OperationalError) no such table: scheduled_job
2025-06-21T17:00:01.326012221Z [SQL: SELECT scheduled_job.id AS scheduled_job_id, scheduled_job.name AS scheduled_job_name, scheduled_job.scheduled_time AS scheduled_job_scheduled_time, scheduled_job.status AS scheduled_job_status, scheduled_job.created_at AS scheduled_job_created_at, scheduled_job.updated_at AS scheduled_job_updated_at, scheduled_job.user_id AS scheduled_job_user_id, scheduled_job.template_id AS scheduled_job_template_id, scheduled_job.segment_id AS scheduled_job_segment_id, scheduled_job.smtp_config_id AS scheduled_job_smtp_config_id, scheduled_job.from_email AS scheduled_job_from_email, scheduled_job.from_name AS scheduled_job_from_name, scheduled_job.started_at AS scheduled_job_started_at, scheduled_job.completed_at AS scheduled_job_completed_at, scheduled_job.current_batch AS scheduled_job_current_batch, scheduled_job.batch_size AS scheduled_job_batch_size, scheduled_job.total_emails AS scheduled_job_total_emails, scheduled_job.sent_emails AS scheduled_job_sent_emails, scheduled_job.failed_emails AS scheduled_job_failed_emails, scheduled_job.opened_emails AS scheduled_job_opened_emails, scheduled_job.clicked_emails AS scheduled_job_clicked_emails, scheduled_job.sending_started_at AS scheduled_job_sending_started_at, scheduled_job.sending_completed_at AS scheduled_job_sending_completed_at, scheduled_job.avg_sending_rate AS scheduled_job_avg_sending_rate, scheduled_job.use_optimal_time AS scheduled_job_use_optimal_time, scheduled_job.optimal_time_window_start AS scheduled_job_optimal_time_window_start, scheduled_job.optimal_time_window_end AS scheduled_job_optimal_time_window_end, scheduled_job.optimal_day_preference AS scheduled_job_optimal_day_preference, scheduled_job.actual_send_time AS scheduled_job_actual_send_time 
2025-06-21T17:00:01.326030352Z FROM scheduled_job 
2025-06-21T17:00:01.326033762Z WHERE scheduled_job.status = ? AND scheduled_job.scheduled_time > ?]
2025-06-21T17:00:01.326036922Z [parameters: ('scheduled', '2025-06-21 17:00:01.323758')]
2025-06-21T17:00:01.326039472Z (Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-21T17:00:01.326357952Z INFO:apscheduler.executors.default:Job "check_for_new_jobs (trigger: interval[0:01:00], next run at: 2025-06-21 17:01:01 UTC)" executed successfully
2025-06-21T17:01:01.32584936Z DEBUG:apscheduler.scheduler:Looking for jobs to run
2025-06-21T17:01:01.325875601Z DEBUG:apscheduler.scheduler:Next wakeup is due at 2025-06-21 17:02:01.319828+00:00 (in 59.999061 seconds)
2025-06-21T17:01:01.325883462Z INFO:apscheduler.executors.default:Running job "check_for_new_jobs (trigger: interval[0:01:00], next run at: 2025-06-21 17:02:01 UTC)" (scheduled at 2025-06-21 17:01:01.319828+00:00)
2025-06-21T17:01:01.325888062Z DEBUG:root:Could not check for new jobs: (sqlite3.OperationalError) no such table: scheduled_job
2025-06-21T17:01:01.325893122Z [SQL: SELECT scheduled_job.id AS scheduled_job_id, scheduled_job.name AS scheduled_job_name, scheduled_job.scheduled_time AS scheduled_job_scheduled_time, scheduled_job.status AS scheduled_job_status, scheduled_job.created_at AS scheduled_job_created_at, scheduled_job.updated_at AS scheduled_job_updated_at, scheduled_job.user_id AS scheduled_job_user_id, scheduled_job.template_id AS scheduled_job_template_id, scheduled_job.segment_id AS scheduled_job_segment_id, scheduled_job.smtp_config_id AS scheduled_job_smtp_config_id, scheduled_job.from_email AS scheduled_job_from_email, scheduled_job.from_name AS scheduled_job_from_name, scheduled_job.started_at AS scheduled_job_started_at, scheduled_job.completed_at AS scheduled_job_completed_at, scheduled_job.current_batch AS scheduled_job_current_batch, scheduled_job.batch_size AS scheduled_job_batch_size, scheduled_job.total_emails AS scheduled_job_total_emails, scheduled_job.sent_emails AS scheduled_job_sent_emails, scheduled_job.failed_emails AS scheduled_job_failed_emails, scheduled_job.opened_emails AS scheduled_job_opened_emails, scheduled_job.clicked_emails AS scheduled_job_clicked_emails, scheduled_job.sending_started_at AS scheduled_job_sending_started_at, scheduled_job.sending_completed_at AS scheduled_job_sending_completed_at, scheduled_job.avg_sending_rate AS scheduled_job_avg_sending_rate, scheduled_job.use_optimal_time AS scheduled_job_use_optimal_time, scheduled_job.optimal_time_window_start AS scheduled_job_optimal_time_window_start, scheduled_job.optimal_time_window_end AS scheduled_job_optimal_time_window_end, scheduled_job.optimal_day_preference AS scheduled_job_optimal_day_preference, scheduled_job.actual_send_time AS scheduled_job_actual_send_time 
2025-06-21T17:01:01.325908233Z FROM scheduled_job 
2025-06-21T17:01:01.325911823Z WHERE scheduled_job.status = ? AND scheduled_job.scheduled_time > ?]
2025-06-21T17:01:01.325914103Z [parameters: ('scheduled', '2025-06-21 17:01:01.321089')]
2025-06-21T17:01:01.325916053Z (Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-21T17:01:01.325920923Z INFO:apscheduler.executors.default:Job "check_for_new_jobs (trigger: interval[0:01:00], next run at: 2025-06-21 17:02:01 UTC)" executed successfully
2025-06-21T17:02:01.321745447Z DEBUG:apscheduler.scheduler:Looking for jobs to run
2025-06-21T17:02:01.376672643Z DEBUG:apscheduler.scheduler:Next wakeup is due at 2025-06-21 17:03:01.319828+00:00 (in 59.999346 seconds)
2025-06-21T17:02:01.376741116Z INFO:apscheduler.executors.default:Running job "check_for_new_jobs (trigger: interval[0:01:00], next run at: 2025-06-21 17:03:01 UTC)" (scheduled at 2025-06-21 17:02:01.319828+00:00)
2025-06-21T17:02:01.376755036Z DEBUG:root:Could not check for new jobs: (sqlite3.OperationalError) no such table: scheduled_job
2025-06-21T17:02:01.376762326Z [SQL: SELECT scheduled_job.id AS scheduled_job_id, scheduled_job.name AS scheduled_job_name, scheduled_job.scheduled_time AS scheduled_job_scheduled_time, scheduled_job.status AS scheduled_job_status, scheduled_job.created_at AS scheduled_job_created_at, scheduled_job.updated_at AS scheduled_job_updated_at, scheduled_job.user_id AS scheduled_job_user_id, scheduled_job.template_id AS scheduled_job_template_id, scheduled_job.segment_id AS scheduled_job_segment_id, scheduled_job.smtp_config_id AS scheduled_job_smtp_config_id, scheduled_job.from_email AS scheduled_job_from_email, scheduled_job.from_name AS scheduled_job_from_name, scheduled_job.started_at AS scheduled_job_started_at, scheduled_job.completed_at AS scheduled_job_completed_at, scheduled_job.current_batch AS scheduled_job_current_batch, scheduled_job.batch_size AS scheduled_job_batch_size, scheduled_job.total_emails AS scheduled_job_total_emails, scheduled_job.sent_emails AS scheduled_job_sent_emails, scheduled_job.failed_emails AS scheduled_job_failed_emails, scheduled_job.opened_emails AS scheduled_job_opened_emails, scheduled_job.clicked_emails AS scheduled_job_clicked_emails, scheduled_job.sending_started_at AS scheduled_job_sending_started_at, scheduled_job.sending_completed_at AS scheduled_job_sending_completed_at, scheduled_job.avg_sending_rate AS scheduled_job_avg_sending_rate, scheduled_job.use_optimal_time AS scheduled_job_use_optimal_time, scheduled_job.optimal_time_window_start AS scheduled_job_optimal_time_window_start, scheduled_job.optimal_time_window_end AS scheduled_job_optimal_time_window_end, scheduled_job.optimal_day_preference AS scheduled_job_optimal_day_preference, scheduled_job.actual_send_time AS scheduled_job_actual_send_time 
2025-06-21T17:02:01.376767007Z FROM scheduled_job 
2025-06-21T17:02:01.376772037Z WHERE scheduled_job.status = ? AND scheduled_job.scheduled_time > ?]
2025-06-21T17:02:01.376776237Z [parameters: ('scheduled', '2025-06-21 17:02:01.321928')]
2025-06-21T17:02:01.376780247Z (Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-21T17:02:01.376785747Z INFO:apscheduler.executors.default:Job "check_for_new_jobs (trigger: interval[0:01:00], next run at: 2025-06-21 17:03:01 UTC)" executed successfully
2025-06-21T17:02:25.705907423Z 10.214.17.52 - - [21/Jun/2025:17:02:25 +0000] "GET / HTTP/1.1" 302 199 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"
2025-06-21T17:02:26.114631488Z 10.214.210.208 - - [21/Jun/2025:17:02:26 +0000] "GET /login HTTP/1.1" 200 5295 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"
2025-06-21T17:02:26.461632147Z 10.214.17.52 - - [21/Jun/2025:17:02:26 +0000] "GET /static/css/tooltips.css HTTP/1.1" 200 0 "https://emailcampaignmanager.onrender.com/login" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"
2025-06-21T17:02:26.925059111Z 10.214.17.52 - - [21/Jun/2025:17:02:26 +0000] "GET /static/js/tooltips.js HTTP/1.1" 200 0 "https://emailcampaignmanager.onrender.com/login" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"
2025-06-21T17:02:26.967970041Z 10.214.210.208 - - [21/Jun/2025:17:02:26 +0000] "GET /static/css/custom.css HTTP/1.1" 200 0 "https://emailcampaignmanager.onrender.com/login" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"
2025-06-21T17:02:42.219407876Z INFO:root:Login form submitted for username: admin
2025-06-21T17:02:42.329535419Z ERROR:app:Exception on /login [POST]
2025-06-21T17:02:42.32956531Z Traceback (most recent call last):
2025-06-21T17:02:42.32957135Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
2025-06-21T17:02:42.3295765Z     self.dialect.do_execute(
2025-06-21T17:02:42.32958147Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
2025-06-21T17:02:42.32958623Z     cursor.execute(statement, parameters)
2025-06-21T17:02:42.329590671Z sqlite3.OperationalError: no such table: user
2025-06-21T17:02:42.329594841Z 
2025-06-21T17:02:42.329600031Z The above exception was the direct cause of the following exception:
2025-06-21T17:02:42.329604561Z 
2025-06-21T17:02:42.329608691Z Traceback (most recent call last):
2025-06-21T17:02:42.329613901Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
2025-06-21T17:02:42.329618652Z     response = self.full_dispatch_request()
2025-06-21T17:02:42.329622692Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329627882Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
2025-06-21T17:02:42.329632402Z     rv = self.handle_user_exception(e)
2025-06-21T17:02:42.329636692Z          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329640852Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
2025-06-21T17:02:42.329645212Z     rv = self.dispatch_request()
2025-06-21T17:02:42.329663943Z          ^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329668303Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
2025-06-21T17:02:42.329672423Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2025-06-21T17:02:42.329676703Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329681484Z   File "/opt/render/project/src/routes.py", line 53, in login
2025-06-21T17:02:42.329685884Z     ).first()
2025-06-21T17:02:42.329689904Z       ^^^^^^^
2025-06-21T17:02:42.329694374Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2759, in first
2025-06-21T17:02:42.329698414Z     return self.limit(1)._iter().first()  # type: ignore
2025-06-21T17:02:42.329717015Z            ^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329720295Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2857, in _iter
2025-06-21T17:02:42.329723025Z     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
2025-06-21T17:02:42.329725725Z                                                   ^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329728305Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
2025-06-21T17:02:42.329731255Z     return self._execute_internal(
2025-06-21T17:02:42.329733905Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329740076Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
2025-06-21T17:02:42.329743246Z     result: Result[Any] = compile_state_cls.orm_execute_statement(
2025-06-21T17:02:42.329746126Z                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329748636Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
2025-06-21T17:02:42.329751076Z     result = conn.execute(
2025-06-21T17:02:42.329753786Z              ^^^^^^^^^^^^^
2025-06-21T17:02:42.329756726Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
2025-06-21T17:02:42.329759486Z     return meth(
2025-06-21T17:02:42.329762636Z            ^^^^^
2025-06-21T17:02:42.329767866Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
2025-06-21T17:02:42.329770887Z     return connection._execute_clauseelement(
2025-06-21T17:02:42.329773797Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329776617Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
2025-06-21T17:02:42.329779187Z     ret = self._execute_context(
2025-06-21T17:02:42.329782087Z           ^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329784817Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
2025-06-21T17:02:42.329787687Z     return self._exec_single_context(
2025-06-21T17:02:42.329790647Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-21T17:02:42.329793217Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
2025-06-21T17:02:42.329795958Z     self._handle_dbapi_exception(
2025-06-21T17:02:42.329798658Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
2025-06-21T17:02:42.329801218Z     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2025-06-21T17:02:42.329803818Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
2025-06-21T17:02:42.329809458Z     self.dialect.do_execute(
2025-06-21T17:02:42.329812268Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
2025-06-21T17:02:42.329815288Z     cursor.execute(statement, parameters)
2025-06-21T17:02:42.329836459Z sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
2025-06-21T17:02:42.329840499Z [SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.created_at AS user_created_at, user.last_login AS user_last_login, user.email_verified AS user_email_verified, user.is_active AS user_is_active, user.verification_token AS user_verification_token, user.verification_token_expires AS user_verification_token_expires, user.reset_password_token AS user_reset_password_token, user.reset_token_expires AS user_reset_token_expires, user.is_admin AS user_is_admin, user.permissions AS user_permissions 
2025-06-21T17:02:42.329849279Z FROM user 
2025-06-21T17:02:42.329852299Z WHERE user.username = ? OR user.email = ?
2025-06-21T17:02:42.329855549Z  LIMIT ? OFFSET ?]
2025-06-21T17:02:42.329857869Z [parameters: ('admin', 'admin', 1, 0)]
2025-06-21T17:02:42.32986073Z (Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-21T17:02:42.330931996Z 10.214.17.52 - - [21/Jun/2025:17:02:42 +0000] "POST /login HTTP/1.1" 500 265 "https://emailcampaignmanager.onrender.com/login" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"